# Generated by Django 5.1.4 on 2025-01-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("book_title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, max_length=100)),
                ("year_of_publication", models.IntegerField(blank=True)),
                ("book_author", models.CharField(max_length=50)),
                ("summary", models.TextField(blank=True, max_length=6000)),
                ("img_url", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "book",
            },
        ),
    ]
